name: Run RAG Notebook

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-notebook:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        # Limpiamos instalaciones previas de GitHub
        pip uninstall -y torch torchvision torchaudio bitsandbytes
        # Instalamos todo desde el requirements controlado
        pip install -r requirements.txt
        # Instalamos herramientas de ejecución
        pip install nbconvert ipykernel

    - name: Execute notebook
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        jupyter nbconvert --to notebook --execute notebooks/Proyecto_RAG_paraGit.ipynb --output ../resultado_rag.ipynb

    - name: Upload result
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: notebook-final
        path: resultado_rag.ipynb